name: Checkout Branches

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch 1
        uses: actions/checkout@v2
        with:
          ref: master
          path: branch1

      # Perform actions specific to branch 1
      - name: Run Tests on Branch 1
        run: |
          echo "The path of code from branch 1 is: ${{ github.workspace }}/branch1"

      - name: Checkout Branch 2
        uses: actions/checkout@v2
        with:
          ref: develop
          path: branch1/branch2

      # Perform actions specific to branch 2
      - name: Run Tests on Branch 2
        run: |
          echo "The path of code from branch 2 is: ${{ github.workspace }}/branch1/branch2"
          
      - name: Zip Branch2
        run: |
          cd branch1
          zip -r branch2.zip branch2
      - name: Get Zip File Path
        run: |
          echo "The path of the zip file is: ${{ github.workspace }}/branch1/branch2.zip"

