name: test

on:
  push:
    branches: [ master ]

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: Directory Creation 
        run: |
          ls .
          mkdir iasp_cicd && mkdir iasp_cicd/appcode
          cd iasp_cicd
          git clone -b develop https://github.com/javaashwin/WebGoat.git
          ls .
          cd ..
          ls $GITHUB_WORKSPACE

