name: My Workflow
on:
  push:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Run shell commands
        run: |
          echo "Hello, world!"
          ls -la
          pwd
          sudo apt update
          sudo apt install -y python3
          sudo apt install -y python3-pip
          python --version
          pip3 --version
          sudo mkdir -p iasp_cicd
          cd iasp_cicd
          sudo mkdir -p appcode
          sudo cp -r /home/runner/work/my-project-1/my-project-1/. ./appcode
          ls ./appcode
          cd ./appcode
          zip -r sourcecode.zip ./*
          cd ..
          ls .
          echo "testing"
          

