name: test

on:
  push:
    branches: [ master ]

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - name: Directory Creation 
        run: |
          echo "testing code"
          ls .


