name: test

on:
  push:
    branches: [ master ]

jobs:
 name-of-job:
   runs-on: ubuntu-latest
   steps:
    #- name: Directory Creation 
      # run: |
        # cd ~
         # cd /
        # sudo mkdir iasp_cicd
        # cd iasp_cicd
        # sudo mkdir appcode
       #  ls .
      #   cd ..
     #    ls .
    #- name: Checkout client sourcecode
     # uses: actions/checkout@v3
     # with:
       #path: iasp_cicd/appcode
  #  - name: checking if source coode is checked out in appcode folder
   #   run: |
    #     pwd
     #    cd iasp_cicd
      #   ls .     
       ##  cd appcode
         #ls .
  #  - name: iasp code fetch
  #    uses: actions/checkout@v3
  #    with:
  #      ref: develop
   #     repository: javaashwin/WebGoat
   #     path: iasp_cicd
    - name: source code zip of client 
      run: |
         cd ~
         cd / 
         sudo mkdir iasp_cicd
         cd iasp_cicd
         sudo git clone -b develop https://github.com/javaashwin/WebGoat.git
         ls .
         cd WebGoat
         ls .
         sudo mkdir appcode
         cd appcode
         sudo git clone -b master https://github.com/javaashwin/my-project-1.git
         ls .
         cd ..
         sudo zip -r clientsourcecode.zip appcode/my-project-1
         
       #  ls .
        # cd ..
        # zip -r clientsourcecode.zip  appcode/
        # cd appcode
        # ls .
      
    


