name: Checkout Branches

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code in iasp_cicd
        uses: actions/checkout@v2
        with:
          ref: master
          path: iasp_cicd

      # Perform actions specific to branch 1
      - name: Run Tests on Branch 1
        run: |
          echo "The path of code from branch 1 is: ${{ github.workspace }}/branch1"

      - name: Checkout client sourcecode inside appcode folder
        uses: actions/checkout@v2
        with:
          ref: develop
          path: iasp_cicd/appcode
        

      # Perform actions specific to branch 2
      - name: Run Tests on Branch 2
        run: |
          echo "The path of code from branch 2 is: ${{ github.workspace }}/branch1/branch2"
          
      - name: Zip Branch2
        run: |
          cd iasp_cicd
          cd appcode
          ls .
          cd ..
          zip -r clientsourcecode.zip appcode
      - name: Get Zip File Path
        run: |
          echo "The path of the zip file is: ${{ github.workspace }}/iasp_cicd/clientsourcecode.zip"
          
      - name: Get file path
        run: |
          export FILEPATH="${{ github.workspace }}/iasp_cicd/clientsourcecode.zip"
          echo "$FILEPATH"
          export "CLIENT_ID: ${{vars.CLIENT_ID}}"
          echo "$CLIENT_ID"          
          
          
          


