name: test

on:
  push:
    branches: [ master ]

jobs:
 name-of-job:
   runs-on: ubuntu-latest
   steps:
    - name: Directory Creation 
      run: |
         mkdir iasp_cicd
         cd iasp_cicd
         mkdir appcode
         cd ..
    - name: Checkout client sourcecode
      uses: actions/checkout@v3
      with:
       path: iasp_cicd/appcode
    - name: iasp code fetch
      uses: actions/checkout@v3
      with:
        ref: develop
        repository: javaashwin/WebGoat
        path: iasp_cicd
    - name: source code zip of client 
      run: |
          cd iasp_cicd/appcode
          zip -r clientsourcecode.zip  appcode/
          ls .
          cd ..
          ls .
      
    


